sonar.projectKey=Abhi122005_Exam-Seating
sonar.organization=abhi122005
sonar.sources=apps/web/src,services/parser
sonar.tests=apps/web/src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/.venv/**,**/.git/**,**/coverage/**,**/dist/**,**/*.d.ts,apps/web/public/**,docs/**,.github/**
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.typescript.tsconfigPath=apps/web/tsconfig.json
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false
sonar.coverage.exclusions=services/parser/**,**/*.test.ts
